config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root "locations#index"
	get "locations/index" => "locations#index"
	resources :shops, only: [:show, :index, :mallShop]
	resources :locations, only: [:index, :intro ,:cityscape0, :cityscape1, :gotoprev, :gotonext]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	#asociation
	belongs_to :street
	has_many :shops
	
	#validation
	validates :street_id, inclusion: { in: 0..100 }
end

app/models/operation_hour.rb
class OperationHour < ApplicationRecord
	belongs_to :shop
	
	#validation
	#validates :close1, allow_nil: true #(まだ入れてないifで詰まったら)
	#validates :open2, allow_nil: true
end

app/models/shop.rb
class Shop < ApplicationRecord
	belongs_to :location ,optional: true
	has_many :operationHours
	
end

app/models/street.rb
class Street < ApplicationRecord
	has_many :locations
	
	#joinsの実験
	#Street.joins(:locations)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	require 'mechanize'
	require 'uri'
	require 'date'

	def cityscape0
	end
	
	def cityscape1
	end
	
	def gotoprev
	end
	
	def gotonext
	end
	
	def intro
	end

	def index
		p "hellow world again! from location action index"
		search
		p @street_num
		if @street_num.blank?
			@street_num=1
		else
			@street_num=@street_num.to_i	#p "@street_numは#{@street_num}"
		end
		@streetSide = Street.find(@street_num)#=>プロペラ通り

			 @renban=@streetSide.street_name.index("(") #番号の順番。14とか。
			 @renban_end=@streetSide.street_name.index(")") #最後のカッコ順番
			if @renban
				#p "連番発生してます"
				@renban_next=@streetSide.street_name.next #＠renban="Omotesando-表参道(3)"
				 @renban_next=Street.find_by(street_name: @renban_next)
					 @renban_s=@renban+1
					 @renban_prev=@streetSide.street_name[@renban_s...@renban_end].to_i-1
					 @name_string=@streetSide.street_name[0...@renban]
					 @renban_prev=Street.find_by(street_name: "#{@name_string}(#{@renban_prev})")
			end
		@renbanAction="color:rgb(1,14,95);"

		#@cityscape0 = Location.includes(:shops).where(street_id: @streetSide.id, side:0).pluck(:id).uniq#=>[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
		#@cityscape1 = Location.includes(:shops).where(street_id: @streetSide.id, side:1).pluck(:id).uniq#=>[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
		@line0shops=Location.where(street_id: 2, side:0).includes(:shops)
		@line1shops=Location.where(street_id: 2, side:1).includes(:shops)
		@many=[@line0shops.length, @line1shops.length].max
		#p "多いサイドの店舗数"
		#p @many
		
		#query_diet#
		##

		#closeShops
		@grayAction = "border: 6px solid gray;"
		@greenAction = "border: 6px solid yellowgreen;"
		@mallCss = "border-radius: 1vh; border: 1px solid navy;"
		@crossingStreet = "background-color: rgba(2, 15, 100, 0.86); box-shadow:none; border-radius: 0vh; border: 0px; color:rgba(255, 250, 214, 1); height: 8vh;"

		#@events = Event.all.limit(5).order('id DESC')#5件制限。降順
		#@random = Random.new
		#@random = @random.rand(1..3)
		##mall実験##、##表示の実験##、##scraping##、##touchmove実験##=>不要
	end
	
#	def closeShops##営業時間反映実験##
#			p "クロー！"
#			@streetSide.id
#			@closeShops_0 = []
#			@closeShops_1 = []
#			@today = Time.zone.now#=>Thu, 24 Dec 2020 12:15:09 JST +09:00
#			@hun = @today.min.to_s
#		  if @hun.length === 1#=>1桁なら0を追加
#		  	@hun = "0"+@hun
#		  end
#		  #p "このtextみれますか？"		
#			p @present = @today.hour.to_s+@hun#=>"2337"
#			
#			#p "ここから@cityscape0"
#			@cityscape0.each do |id| #side0
#				@shopLists = Shop.where(location_id: id).pluck(:id)
#				@shopLists.each do |shopList|
#					@cross_street = Shop.find_by(id: shopList, shop_name: "cross_street")
#					@operationHour = OperationHour.find_by(shop_id: shopList, day: @today.wday)
#					#p "ここまで到達!cross_streetは#{@cross_street}です"
#					p "ここまで到達!shopListは#{shopList}です"
#				end

#					if @cross_street
#						p "Alley-裏通りです"
#					elsif @operationHour.blank?
#						p "店舗ありません"
#					elsif @operationHour.close1.blank?
#						if @operationHour.open1.to_i < @present.to_i && @operationHour.close2.to_i > @present.to_i
#							p "営業時間中"
#						else
#							@shop_id = @operationHour.shop_id
#							@closeShops_0.push(@shop_id)
#							p "shop_id#{@shop_id}しまってます。"
#						end
#					else #close1に値がある
#						if @operationHour.open1.to_i < @present.to_i && @operationHour.close1.to_i > @present.to_i || @operationHour.open2.to_i < @present.to_i && @operationHour.close2.to_i > @present.to_i
#							p "close1に値あって営業中"
#						else
#							@shop_id = @operationHour.shop_id
#							@closeShops_0.push(@shop_id)
#						end
#					end #if @operationHour.blank?の終わり
#			end

			#p "ここから@cityscape1"
#			@cityscape1.each do |id| #side1
#				@shopLists = Shop.where(location_id: id).pluck(:id)
#				@shopLists.each do |shopList|
#					#p "shopをshop_idで調べてるOperationHour"
#					@cross_street = Shop.find_by(id: shopList, shop_name: "cross_street")
#					@operationHour = OperationHour.find_by(shop_id: shopList)
#
#				if @cross_street
#					p "Alley-裏通りです"
##				elsif @operationHour.blank?
#	#				p "店舗ありません"
#	#			elsif @operationHour.close1.blank?
#					if @operationHour.open1.to_i < @present.to_i && @operationHour.close2.to_i > @present.to_i
#						p "営業時間中"
#					else
#						@shop_id = @operationHour.shop_id
#						@closeShops_1.push(@shop_id)
#					end
#				else #close1に値がある
#					if @operationHour.open1.to_i < @present.to_i && @operationHour.close1.to_i > @present.to_i || @operationHour.open2.to_i < @present.to_i && @operationHour.close2.to_i > @present.to_i
#						p "close1に値あって営業中"
#					else
#						@shop_id = @operationHour.shop_id
#						@closeShops_1.push(@shop_id)
#					end
#				end
#			end#shopList.each終わり
#			end
#	end#closeShops終わり#
	
	def search##あいまい検索実験=>ストリート表示##
			params[:search]
			@streetNames=[]
			@s_result=Location.where('location LIKE (?)',"%#{params[:search]}%")
				if !@s_result.blank?
					@street_ids=@s_result.pluck(:street_id).uniq#uniqは重複削除
					@street_ids.each do |street_id|
						 @streetRec=Street.find_by(id: street_id)
						 @streetNames.push(@streetRec)
					end
				else
					#p "ありませーーん！"
				end
			 @streetNames=@streetNames.compact#nil要素を削除
			 
				if params[:commit].blank?
					@street_num=1
					#p "commit.blankに来てます"
				else
					#p @street_num=params[:commit]
					@street_num.to_i
					#p "commit受け取ったよー！"
				end
	end##検索実験終わり##
	


	 helper_method :search
	# helper_method :closeShops

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	
	def show#render partialでは使わない
		#p "Shopsコントローラのshowですよ"
	end
	
	def index#お問い合わせ
	end
	
	def mallShop#モール内店舗
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Streetindex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.2.1/font-awesome-animation.min.css">
    <meta name="viewport"content="width=device-width,initial-scale=1,maximum-scale=1"><!--禁止minimum-scale=1.0,user-scalable=no"-->
    <meta name="description" content="Harajuku(裏原) Map. 表参道・竹下通りなどストリートごとに表示し、1階以外のお店も一目で発見できる、お散歩サポートサイト。">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_cityscape0.html.erb
<p id="anchor" class="closeShops<%= @closeShops_0 %>"></p>

		<% @line0shops.each.with_index do |line0shop, index| %><!--location数-->
			<% @mmm=line0shop.shop_ids.size() %>
				<% if @mmm>5 %><%#= "mallの定義" %>
					<% @mall0=index %>
				<% end %>

			<% line0shop.shops.each.with_index do |shop, inde| %><!--shop数-->

				<%# Mall %>
				<% if index==@mall0 %>
				<% @lef = 9+24*index %>
					<ul id="bldg<%= index %>" class="shops" style="top:23vh; left:<%= @lef %>vw;
						<%= @mallCss %>
					">
						<span class="shop_name"><%= line0shop.location.split(",", 2)[1] %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, each_bldg: line0shop, status: @mall0} %>
					</ul>

				<%# Street_nameあり %>
				<% elsif shop.shop_name=="cross_street" && line0shop.location!="Alley-裏通り" %><%#= "cross_st" %>
				<% @st=9999 %>
				<% @lef = 9+24*index %>
					<ul id="bldg<%= index %>" class="shops" style="top:23vh; left:<%= @lef %>vw;
						<%= @crossingStreet %>
					">
						<span class="shop_name"><%= line0shop.location.split("-", 2)[0] %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, each_bldg: line0shop, status: @st } %>
					</ul>
				
				<%# 裏通り %>
				<% elsif line0shop.location=="Alley-裏通り" %>
				<% @st=1 %>
				<% @lef = 9+24*index %>
					<ul id="bldg<%= index %>" class="shops" style="top:23vh; left:<%= @lef %>vw;
						<%= @crossingStreet %>
					">
						<span class="shop_name"><%= "" %></span>
						<%#= render partial: "shops/show", locals: { shopInfo: shop, each_bldg: line0shop, status: @st } %>
					</ul>

				<%# shop:隣の2階以上 %>
				<% elsif index > 0 && inde >=1 then %>
					<% @lef = 9+24*index %><!--動的に要素のtop&leftを変更-->
					<% @tp = 22.1-7*inde %><!--24.8-4.8>43.2-5>17-5-->
					<ul id="bldg<%= index %>" class="shops" style="top:<%= @tp %>vh; left:<%= @lef %>vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, each_bldg: line0shop, status: index } %>
					</ul>

				<%# shop:隣の1階 %>
				<% elsif index > 0 then %>
					<% @lef = 9+24*index %><!--動的に要素のleftを変更-->
					<ul id="bldg<%= index %>" class="shops" style="top:23vh; left:<%= @lef %>vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, each_bldg: line0shop, status: index } %>
					</ul>

				<%# shop:最初の2階以上 %>
				<% elsif index == 0 && inde >= 1 then %>
					<% @tp = 22.1-7*inde %>
					<ul id="bldg0" class="shops" style="top:<%= @tp %>vh; left:9vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, each_bldg: line0shop, status: index } %>
					</ul>

				<%# shop:最初の建物 %>
				<% elsif index == 0 && inde == 0 then %>
					<ul id="bldg0" class="shops" style="top:23vh; left:9vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, each_bldg: line0shop, status: "最初" } %>
					</ul>

				<% end %>
			<% end %>
		<% end %>

app/views/locations/_cityscape1.html.erb
<p id="anchor" class="closeShops<%= @closeShops_1 %>"></p>

		<% @line1shops.each.with_index do |line1shop, index| %><!--location数-->
			<% @mmm=line1shop.shop_ids.size() %>
				<% if @mmm>5 %><%#= "mallの定義" %>
					<% p @Mall1=index %>
				<% end %>

			<% line1shop.shops.each.with_index do |shop, inde| %><!--shop数-->

				<%# Mall %>
				<% if index==@Mall1 %>
				<% @lef = 9+24*index %>
					<ul id="bldg<%= index %>" class="shops" style="top:39.3vh; left:<%= @lef %>vw;
						<%= @mallCss %>
					">
						<span class="shop_name"><%= line1shop.location.split(",", 2)[1] %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, status: index, each_bldg: line1shop } %>
					</ul>

				<%# Street_nameあり %>
				<% elsif shop.shop_name=="cross_street" && line1shop.location!="Alley-裏通り" %><%#= "cross_st" %>
				<% @lef = 9+24*index %>
				<% @st=9999 %>
					<ul id="bldg<%= index %>" class="shops" style="top:39.3vh; left:<%= @lef %>vw;
						<%= @crossingStreet %>
					">
						<span class="shop_name"><%= line1shop.location.split("-", 2)[0] %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, status: @st, each_bldg: line1shop } %>
					</ul>
				
				<%# 裏通り %>
				<% elsif line1shop.location=="Alley-裏通り" %>
				<% @lef = 9+24*index %>
				<% @st=1 %>
					<ul id="bldg<%= index %>" class="shops" style="top:39.3vh; left:<%= @lef %>vw;
						<%= @crossingStreet %>
					">
						<span class="shop_name"><%= "" %></span>
						<%#= render partial: "shops/show", locals: { id: shop.id, locationId: index, each_bldg: line0shop } %>
					</ul>

				<%# shop:隣の2階以上 %>
				<% elsif index > 0 && inde >=1 then %>
					<% @lef = 9+24*index %><!--動的に要素のtop&leftを変更-->
					<% @tp = 38.1+7.8*inde %><!--24.8-4.8>43.2-5>17-5-->
					<ul id="bldg<%= index %>" class="shops" style="top:<%= @tp %>vh; left:<%= @lef %>vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, status: index, each_bldg: line1shop } %>
					</ul>

				<%# shop:隣の1階 %>
				<% elsif index > 0 then %>
					<% @lef = 9+24*index %><!--動的に要素のleftを変更-->
					<ul id="bldg<%= index %>" class="shops" style="top:39.3vh; left:<%= @lef %>vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, status: index, each_bldg: line1shop } %>
					</ul>

				<%# shop:最初の2階以上 %>
				<% elsif index == 0 && inde >= 1 then %>
					<% @tp = 38.1+7.8*inde %>
					<ul id="bldg0" class="shops" style="top:<%= @tp %>vh; left:9vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, status: index, each_bldg: line1shop } %>
					</ul>

				<%# shop:最初の建物 %>
				<% elsif index == 0 && inde == 0 then %>
					<ul id="bldg0" class="shops" style="top:39.3vh; left:9vw;
								background-image: url(<%#= @tenant.logo_url %>);">
						<span class="shop_name"><%= shop.shop_name %></span>
						<%= render partial: "shops/show", locals: { shopInfo: shop, status: "最初" , each_bldg: line1shop } %>
					</ul>

				<% end %>
			<% end %>
		<% end %>

app/views/locations/_gotonext.html.erb
<div id="gotoNext">
		<%= form_with(url: "/", method: :get, local: true) do %>
	<a>Go to <br>
			<% if @renban_next.nil? %>
				<%= @renban_next="" %> 
			<a data-style="gotoStreet">[Yes]
				<%= submit_tag "", disabled: true %>
			<% else %>
				<span class="gotoStName"><%= @renban_next.street_name %> ?</span><br>
			<a data-style="gotoStreet">[Yes]
				<%= submit_tag "#{@renban_next.id}", data:{style:"gotoStreet"}, disabled: false %>
			<% end %>
	</a>

	<a id="renban_no", class="info_fadeout", data-style="gotoStreet">[No]</a>
		<% end %>
</div>

app/views/locations/_gotoprev.html.erb
<div id="gotoPrev">
		<%= form_with(url: "/", method: :get, local: true) do %>
	<a>Go to <br>
			<% if @renban_prev.nil? %>
				<%= @renban_prev="" %> 
			<a data-style="gotoStreet">[Yes]
				<%= submit_tag "", disabled: true %>
			<% else %>
				<span class="gotoStName"><%= @renban_prev.street_name %> ?</span><br>
			<a data-style="gotoStreet">[Yes]
				<%= submit_tag "#{@renban_prev.id}", data:{style:"gotoStreet"}, disabled: false %>
			<% end %>
	</a>

	<a id="renban_no", class="info_fadeout", data-style="gotoStreet">[No]</a>
		<% end %>
</div>

app/views/locations/_intro.html.erb
<div class="whatishere_wrap">
	<div class="whatishere">
			<h5>What's this?</h5>
				<p>You can check all shops on the each street around Harajuku.<br>
				ストリートごとお店リスト、お散歩サポートサイト</p>
				<br>
			<h5>News&Update</h5>
				<p>2021/5  DB更新, CatStreet&表参道 追加</p>
				<p>2021/4  DB作成</p>
				<p>2021/2  デプロイ</p>
				<br>
			<h5>ContactUs</h5>
				<h6>♦︎For Harajuku Guest </h6>
				<h6>-原宿で街歩きする方々へ-</h6>
				<p>please let us know if shops are out of business.<br>
				お店が変わっていたら教えてください。<br>
				すぐに最新の情報に反映します。</p>
				<a href="mailto:moshimoshi.streetindex＠gmail.com&subject=[ChangeShops]" class="mailto">email</a>
				<h6>♦︎For Shop owner</6h>
				<h6>-店舗・事業者さま︎-</6h>
				<p>(1)Shop Logo</p>
				<p>We can edit shop's name to logo soon.</p>
				<p>トップページの店舗名をロゴに変更可能となっております。</p>
				<a href="mailto:moshimoshi.streetindex＠gmail.com&subject=[Logos]" class="mailto">email</a>
				<p>(2)Photos</p>
				<p>It's available upload 5 imgs in the shop details.</p>
				<p>店舗の詳細欄に写真5点掲載可能です。<br>
				店舗入り口、お客様に見せたい商品・<br>
				お料理・サービスなどを送って頂ければ、<br>
				すぐに掲載させて頂きます。</p><br>
				<a href="mailto:moshimoshi.streetindex＠gmail.com&subject=[Imgs]" class="mailto">email</a>
				<p>(3)The hashtag-ハッシュタグ</p>
				<p>Also available add/edit hashtags in the shop details.</p>
				<p>店舗の詳細欄にハッシュタグがあります。<br>
				すぐにご希望のハッシュタグに変更可能となっております。<br>
				お気軽にお問い合わせください。</p><br>
		<a href="mailto:moshimoshi.streetindex＠gmail.com&subject=[Hash]" class="mailto">email</a>
	</div><!--whatishere終わり-->
</div><!--wrap終わり-->

app/views/shops/_index.html.erb
<h5>ストリートインデックス運営事務局</h5>
<p>ご意見、ご感想<br>moshimoshi.streetindex＠gmail.com</p>

app/views/shops/_show.html.erb
<% shopInfo %>
<% each_bldg %>
<% status %>
<% @imgSequences=[1,2,3,4,5] %>

	<li class="hidei">
		<div id="info_fadeout" class="info_fadeout">×</div>

		<!--mall-->
	<% if status==5 %>
			<div id="mall_name">
				<%= each_bldg.location.split(",", 2)[1] %>
			</div>

			<div id="mallInfo_wrap">
			<ul id="mallInfo">
			<% @tenants=Shop.where(location_id: each_bldg.id).order(floor: 'DESC').each do |tenant| %>
				<li class="tenants" style="background-image: url(<%#= tenant.logo_url %>); 
				background-size: contain; background-repeat: no-repeat; background-position-x: center;
					<%# if !@closeShops_0.find{|n|n == tenant.id} || !@closeShops_1.find{|n|n == tenant.id} then %>
						<%#= @greenAction %>
					<%# else %>
						<%#= @grayAction %>
					<%# end %>
				">
					<%# if tenant.logo_url.blank? %><!--承諾後-->
						<span class="shop_nameMall"><%= tenant.shop_name %></span>
					<%# end %><!--モール店舗詳細-->
				</li>
				<%= render partial: 'shops/mallShop', locals: {tanakoInfo: tenant } %>
			<% end %><!--@tenants.eachのend-->
					
			</ul>
			</div>

		<!--streetInfo-->
	<% elsif status==9999 %><%# elsif @exception==61 %>
			<div id="mall_name">
				<%= each_bldg.location %>
			</div>

			<div id="shop_img_grid_contaier">
				<%# @location_ids=Location.where.not(street_id: @streetInfo.id).sample(8).pluck(:id) %>
				<% @stid=Street.find_by(street_name: each_bldg.location) %>
				<% @along_st=Location.where(id: @stid).includes(:shops).pluck(:s_img1) %>
				<%# @shopImgBag=[] %>
				<%# @location_ids.each do |id| %>
					<%# @shopImg=Shop.find_by(location_id: id) %>
					<%# if @shopImg&.s_img1 %>
						<%# @shopImgBag.push(@shopImg.s_img1) %>
					<%# else %>
						<%# p "画像ありません" %>
					<%# end %>
				<%# end %>
				<% @along_st.reject(&:blank?) %>
				<% if @along_st.length<5 %>
					<div id="shop_img1" style="background-image:url(<%= asset_path 'eat_img1.png' %>)"></div>
					<div id="shop_img2" style="background-image:url(<%= asset_path 'sa_img2.png' %>)"></div>
					<div id="shop_img3" style="background-image:url(<%= asset_path 'sh_img3.png' %>)"></div>
					<div id="shop_img4" style="background-image:url(<%= asset_path 'sa_img4.png' %>)"></div>
					<div id="shop_img5" style="background-image:url(<%= asset_path 'eat_img5.png' %>)"></div>

				<% else %>
					<% @along_st.sample(5).each_with_index do |img, index| %>
						<div id="shop_img<%= index+1 %>" style="background-image:url(<%= img %>)"></div>
					<% end %>
				<% end %>
			</div>

			<div id="enterStreet">
				<a>Go to <br>
				<%= each_bldg.location %> ?</a><br>
				<%= form_with(url: "/", method: :get, local: true) do %>
				<a data-style="gotoStreet">[Yes]
					<% if status==1 %><%# 裏通り %>
						<% @keepout=true %>
					<% else %>
						<% @keepout=false %>
					<% end %>
					<%= submit_tag"#{@stid.id}", data:{style:"gotoStreet"}, disabled: @keepout %></a>
				<a class="info_fadeout", data-style="gotoStreet">[No]</a><!--info_fadeout動いてないjs-->
				<% end %>
			</div>

		<!--shopInfo-->
	<% else %>
			<div id="shop_name"><%= shopInfo.shop_name %></div>
			<div id="shop_img_grid_contaier">
				
				<% @imgSequences.each do |imgSequence| %>
					<% if !eval("shopInfo.s_img#{imgSequence}").blank? %>
						<div id="shop_img<%= imgSequence %>" style="background-image:url(<%= eval("shopInfo.s_img#{imgSequence}" ) %>)"></div>
					<% elsif shopInfo.category.to_s.split("-")[0] =="shopping" %>
						<div id="shop_img<%= imgSequence %>" style="background-image:url(<%= asset_path "sh_img#{imgSequence}.png" %>)"></div>
					<% elsif shopInfo.category.to_s.split("-")[0]=="salon" %>
						<div id="shop_img<%= imgSequence %>" style="background-image:url(<%= asset_path "sa_img#{imgSequence}.png" %>)"></div>
					<% elsif shopInfo.category.to_s.split("-")[0]=="eat&drink" %>
						<div id="shop_img<%= imgSequence %>" style="background-image:url(<%= asset_path "eat_img#{imgSequence}.png" %>)"></div>
					<% else %><!--other-->
						<div id="shop_img<%= imgSequence %>" style="background-image:url(<%= asset_path "other#{imgSequence}.png" %>)"></div>
					<% end %>
				<% end %>
			</div><!--shop_img_grid_contaier-->

			<div class="shop_category">
				<% shopInfo.category.to_s.split("-").each do |i| %>
					<%= "##{i}" %>
				<% end %>
			</div>
			<!--<div class="shop_campaign">Campaign  >></div>-->
			<div class="shop_floor"><%= shopInfo.floor %>F</div>
			<div class="shop_link">
				<% if shopInfo.url %>
					<%= link_to'ShopWebSite',shopInfo.url %>
				<% else %>
					<% link_to'ShopWebSite' %>
				<% end %>
			</div>

	<% end %><!--elseのend-->
</li>